const dummyPosts = [
  {
    likes: 52,
    body: 'Tide Loads of Hope is here to help.  The team is providing free laundry services starting Sunday, August 11th at the Church of Hope 2300 Lakewood Ranch Blvd, Sarasota, FL 34240 operating daily 9 AM – 5 PM local time, or until capacity is reached.',
    timestamp: '2024-08-12T16:50:28+0000',
    permalink: 'https://www.instagram.com/p/C-k8L0tu2y_/',
    igId: 'C-k8L0tu2y_',
    tags: ['Charity'],
    media_url: 'dont need',
    comments: [
      'This is so wonderful can you please come to lemon Grove calif as i run the lemon Grove homeless outreach program',
    ],
  },
  {
    likes: 110,
    body: 'Even the fastest men in the world get stains. When they do, Tide’s got them covered.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-08-12T00:44:23+0000',
    permalink: 'https://www.instagram.com/reel/C-jNkyOOb0Y/',
    igId: 'C-jNkyOOb0Y',

    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: ['I appreciate this so much 😂😂', '😂😂😂', 'Boycotting tide'],
  },
  {
    likes: 99,
    body: 'When it comes to fighting the toughest stains, Tide takes home the gold.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-08-09T17:52:17+0000',
    permalink: 'https://www.instagram.com/reel/C-dUnYHO0sO/',
    igId: 'C-dUnYHO0sO',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      "There's no Tide in France 😭",
      'We love Tide! ❤️',
      '@tidelaundry all day!!',
    ],
  },
  {
    likes: 4743,
    body: 'Even though they’re at the top of their game, nojo18  and carl_lewis_official still get stains. Luckily, there’s Tide.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-08-07T15:04:37+0000',
    permalink: 'https://www.instagram.com/reel/C-X3-Z_OKaJ/',
    igId: 'C-X3-Z_OKaJ',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'a Jamaican, I love washing with Tide. It’s the best American detergent ever. It’s amazing.',
      'Great minds think alike! 👏🏽🏃🏾🥇',
      'I think it would be awsome if you ran side by side with the fastest football player on a football field to help give some perspective on just how fast you really are. I really think things like that will open up some Americans eyes to how fast track stars are. So much respect goes to football, basketball etc and it is well deserved but yall dont get the credit you deserved. Just food for thought. And i will be one of the first to buy your sneakers when they drop',
      'WHO?? 🇨🇦 🤣',
      "Where's the french part",
      'WORLD CHAMPION OF WHAAATTTTT???? 😂😂😂😂😂. United states!? 😢😂',
      'I dislike this',
      'Get those sponsorships and endorsements Noah! 😍😍❤️❤️',
      '🤗💯🇺🇸❤️Love it🤩',
      'Feel better champ',
      'Two of my favs!!',
      'hope hes cleaner than Carl was',
      'FASTEST MAN ALIVE',
      'This is too beautiful to watch.😁🤞❤️',
      'Ratatouille',
      'Carl Lewis dope up legends',
      'When in Rome😂',
    ],
  },
  {
    likes: 88,
    body: 'Congratulations, Noah! We’ll make sure you’re looking your stain-free best. #Paris2024 #Olympics #Partner',
    timestamp: '2024-08-05T08:43:27+0000',
    permalink: 'https://www.instagram.com/p/C-SC4nRuir4/',
    igId: 'C-SC4nRuir4',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: ['Congrats Noah!', '❤️❤️❤️'],
  },
  {
    likes: 101,
    body: 'The road to Olympic glory is full of stains. Thankfully, Tide’s got you covered.\n#Olympics #Paris2024 #Partner',
    timestamp: '2024-08-03T12:50:33+0000',
    permalink: 'https://www.instagram.com/reel/C-NVb3Bu5cl/',
    igId: 'C-NVb3Bu5cl',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      '😍',
      'Can I have a sip',
      'wish would sell this in the UK',
      'Sell tide in Brazil',
    ],
  },
  {
    likes: 101,
    body: 'The toughest stains call for the hardest-working detergent. No matter how you stain, Tide’s got you covered.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-07-30T15:41:26+0000',
    permalink: 'https://www.instagram.com/reel/C-DVrvIO7HE/',
    igId: 'C-DVrvIO7HE',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'Why can’t you guys make a strong scented powder? Why not make the powder with Febreeze in the spring & renewal scent again? Or make a powder with a New Zealand springs scent, or a fruity zesty citrus scent. Don’t get why y’all had to stop making clean breeze powder that was my favorite.',
      'good detergent, greetings from the MIA foundation.',
      'My favorite brand❤️ always bring them back with me to the Netherlands',
      'Cruelty free?',
      'Can you explain your recent shrinkflation? Your bottles used to be 92 fl oz and now they’re down to 84 fl oz at the same price?',
    ],
  },
  {
    likes: 1135,
    body: 'No matter what language you speak, only Tide gets out the toughest stains.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-07-29T21:45:18+0000',
    permalink: 'https://www.instagram.com/reel/C-BasV2uRn-/',
    igId: 'C-BasV2uRn-',
    tags: ['Olympics'],
    media_url: 'dont need',
    comments: [
      'The French laugh 😂',
      'Funny duo! "He is healed." "Give me some hair again!!" #Paris • #2024 • #track',
      'I cannot handle Noah speaking French 🥵',
      'That was interesting.',
      'This is great',
      '“Yall are getting better” Carl: “FROM WHAT” 😂😂😂😂',
      '😂😂😂😂',
      '[french laugh] 😆🥖',
      '😂😂😂😂',
      '😂😂😂',
      '#NoahLyles 🔥🔥🔥🔥 #teamLYLES 💨 #FastestManOnEarth 👏🏽',
    ],
  },
  {
    likes: 594,
    body: 'Game knows game. And when it comes to fighting stains, the legends use Tide.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-07-24T21:17:25+0000',
    permalink: 'https://www.instagram.com/reel/C90feuHPOSJ/',
    igId: 'C90feuHPOSJ',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'What about rolling the shirt 👕 🤔?',
      'When will Tide Evo be available to all? I need it in Free &amp; Gentle.',
      'can never beat the champ',
      'carl was doing too much 😭',
      'I am not happy with the opening ceremony and found it offensive! Proctor and gamble needs to address this! #boycott',
      '@kehdydimy',
    ],
  },
  {
    likes: 53,
    body: 'No matter how hard you compete, stains are no competition for the cleaning power of Tide. #theothergames',
    timestamp: '2024-07-24T13:26:37+0000',
    permalink: 'https://www.instagram.com/reel/C9zpprQOZuR/',
    igId: 'C9zpprQOZuR',
    tags: ['Olympics'],
    media_url: 'dont need',
    comments: [
      'Opening ceremony at Olympics was offensive to the religion of a billion people. Your company needs to address this',
      'CHECK DM’S PLEASE',
    ],
  },
  {
    likes: 6099,
    body: 'Stains happen to the best of us. Even nojo18 and carl_lewis_official. When they do, Tide’s got you covered.\n#Paris2024 #Olympics #TidePartner',
    timestamp: '2024-07-23T21:24:03+0000',
    permalink: 'https://www.instagram.com/reel/C9x7dSQvYkR/',
    igId: 'C9x7dSQvYkR',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'Oh, this is nice! Carl Lewis the best ever! We love Tide in Greece too! 😍❤️❤️',
      "😄 Cute ad! ❤️ Let's go #NoahLyles!! 🇺🇸 #Paris2024",
      'I love this!',
      'This is a great commercial. 🔥🔥🔥🔥',
      'Lllmfao. That last line is so Noah ☠️🤣😭😭😭😭',
      '😂😂😂 “damn!”',
      'Love it coach!',
      'Get you money up sir👏👏👏👏',
      'Love it ❤️🔥',
      'Dang it 😂😂😂😂',
      '😂😂😂😂😂',
      '😂😂😂',
      '❤️',
      'Check yalls lip lol',
      '😂😂😂',
      'Hilarious 😅❤️',
      'Nice 👍🏼',
      'Lebron&gt;you',
      '😂😂',
      'Lowe 🇯🇲🇯🇲🇯🇲🇯🇲wih outta yuh BIG MOUT❗️❗️',
      'Kmt',
      '😂😂😂 love it',
      '💜💜💜💜💜',
      '🔥🔥🔥',
      'Who’s perfect 😉👍🏾',
      'We agree! Stains, messes, and dirty laundry should never get in the way of living life',
      '💪💪💪',
      '😂😂😂😂😂🔥 Carl Lewis :) my ❤️ and Noah 💙 in the same frame. :) 🔥',
    ],
  },
  {
    likes: 178,
    body: 'Khaby Lame knows best, and the best is Tide! America’s #1 laundry detergent brand.\n🌟 Discover the incredible journey of khaby00, the world’s biggest creator, as he dives into America’s wonders! ✨ Join Khaby as he explores the captivating people, places, and things across the nation in his brand-new unscripted series. Khaby is Coming to America is now streaming on tubi! #KhabyLame #ComingToAmerica #tide',
    timestamp: '2024-07-03T18:47:03+0000',
    permalink: 'https://www.instagram.com/p/C8-Juq5v2ZA/',
    igId: 'C8-Juq5v2ZA',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'I saw the comments in a previous post about animal testing. 🥹🥹',
      'When will Evo be available? I have 1 pod left and don’t want to buy more pods! Want Evo!!!',
      '❤️',
    ],
  },
  {
    likes: 67,
    body: 'Tide Loads of Hope and walmart  are here to help, Spencer, IA. proctergamble  is teaming up with m25m_org  to provide free laundry services starting on Saturday, from 9 AM – 5 PM, or until capacity is reached at the Walmart Supercenter at 500 11th St SW Spencer, Iowa 51301.',
    timestamp: '2024-06-28T22:02:45+0000',
    permalink: 'https://www.instagram.com/p/C8xoJqHM2fH/',
    igId: 'C8xoJqHM2fH',
    tags: ['Charity', 'Collab', 'Walmart'],
    media_url: 'dont need',
    comments: [
      'Hi, we had a huge power outage here in Houston, TX. We have a lot of lineman from out of state that have no where to clean their clothes. Is there anyway you can help? TY ❤️',
      'Do you test in animals? Cruelty free?',
    ],
  },
  {
    likes: 91,
    body: 'theclarajones was #TodayYearsOld when she learned that you can lift tough stains with cold water and Tide! Turn to cold with Tide to help the environment + your clothes.\n#TurnToCold #Clean #Laundry​',
    timestamp: '2024-06-24T21:54:40+0000',
    permalink: 'https://www.instagram.com/reel/C8nUACYhJ--/',
    igId: 'C8nUACYhJ--',
    tags: ['Collab'],
    media_url: 'dont need',
    comments: [
      'I use it in my bissell carpet cleaner and upholstery hand held cleaner. PS: fabric car game changer!!!!',
      'Sent dm👏',
      'Great tips!!',
    ],
  },
  {
    likes: 109,
    body: 'Boston was #TodayYearsOld when abbylhoskins  got to drop some knowledge on him: washing clothes in cold water with Tide works on 100% of your most common stains. Tide PODS’ new formula lifts away tough stains on cold, like these grass and dirt stains, and leaves his uniform looking brand new!​\nAnd fun fact: washing on cold is also great for the environment and your wallet! It saves up to 90% of the energy on average in every wash and can save enough electricity to power the average American home for an entire hour when switching from hot to cold!',
    timestamp: '2024-06-21T14:00:49+0000',
    permalink: 'https://www.instagram.com/reel/C8evZbVJFp4/',
    igId: 'C8evZbVJFp4',
    tags: ['Collab'],
    media_url: 'dont need',
    comments: ['Can i eat it ?', 'Tide tastes so good 😍😍'],
  },
  {
    likes: 85,
    body: 'Tide is making sure josephasthetic stays away from tees that ‘used to be white.’ Pick up some Tide with Ultra OXI White + Bright Power PODS so you can stop having to buy a new white tee after every wash. #summerwhites',
    timestamp: '2024-06-20T13:38:23+0000',
    permalink: 'https://www.instagram.com/reel/C8cIB9ouQVL/',
    igId: 'C8cIB9ouQVL',
    tags: ['Collab', 'OXI White'],
    media_url: 'dont need',
    comments: ['Check dm'],
  },
  {
    likes: 95,
    body: '#TidePartner After all these years of laundry, Tide has changed the game with a new formula! 🤯 katiepie07 #TodayYearsOld #TurnToCold #CleanTok #LaundryTok #brandnewinformation #thingsididntknow #motherhoodunplugged #TideColdWater #stainremoval #laundryhack #Tide',
    timestamp: '2024-06-06T21:08:20+0000',
    permalink: 'https://www.instagram.com/reel/C744QI6Odu_/',
    igId: 'C744QI6Odu_',

    tags: ['Collab'],
    media_url: 'dont need',
    comments: [
      'Hello, this is very necessary. Do not buy Tide and Ariel products at their events. Greenleaf is denouncing your products as harmful to health and in various videos they are promoting your products as chemicals in all CIS countries, especially O. performing in Uzbekistan, Tajikistan and Russia.',
      'Why would you wanna use cold. Warm is the best for all situations and it keeps the machine cleaner.',
      'i saw "efficient" and immediately locked in',
      'The hygienic clean saves me and my husband work clothes! 🙌🏼',
    ],
  },
  {
    likes: 128,
    body: '#TidePartner Were you #TodayYearsOld when you learned that turning to cold water with Tide is the ultimate life hack to having 4 girls under the age of 7!​? Stock up on Tide PODS today and switch from hot to cold! #TurnToCold #Clean #Laundry',
    timestamp: '2024-05-30T18:34:04+0000',
    permalink: 'https://www.instagram.com/reel/C7mlKFQIHIr/',
    igId: 'C7mlKFQIHIr',

    tags: ['Cold Water', 'Pods'],
    media_url: 'dont need',
    comments: [
      '❤️👏',
      '👏',
      'Just heard your commercial for groomer month. No shame people. I stopped buying your products 2 years ago. I don’t need you.',
      '🇵🇸',
      '🙌',
    ],
  },
  {
    likes: 70,
    body: 'It was an honor to sponsor the first ever #NationalSTEMFestival presented by usedgov and explr_media, celebrating student achievements in STEM.\nAs part of the event, Tide Senior Scientist Sammy W. sat down with students whose STEM projects are boldly imagining the future of sustainability – from water purification to repurposing food waste for textiles – to discuss how companies can innovate for a more sustainable future.\nWe can’t wait to see what else these incredible students achieve as they pursue educations and careers in #STEM!',
    timestamp: '2024-05-16T13:00:26+0000',
    permalink: 'https://www.instagram.com/p/C7B750jivO6/',
    igId: 'C7B750jivO6',

    tags: ['Sponsor', 'Collab'],
    media_url: 'dont need',
    comments: [
      '#blockout2024 #block 🇵🇸',
      'Free Palestine 🇵🇸🇵🇸',
      "It's wonderful to see young students getting excited about STEM! Their curiosity and enthusiasm today will drive the innovations of tomorrow. 🌟🔬📚 #FutureLeaders #STEMEducation",
      'Blocked! I’m an American and I don’t support the murdering of innocent women and children 🇺🇸🇵🇸',
      'STEM is so important',
      '👍',
      "Don't forget people, Tide has a huge tie to Isnotreal. Isnotreal has b@mbed all the schools and universities in Palestine. Do not be fooled, Tide does not care about anything besides their pockets. They put profits over justice and humanity. If you continue to buy their products you are also complicit! #freepalestine #vivapalestina",
    ],
  },
  {
    likes: 91,
    body: 'It’s easy to see, Tide gives you 3X more clean vs. the leading baking soda detergent.',
    timestamp: '2024-05-15T16:43:35+0000',
    permalink: 'https://www.instagram.com/reel/C6_wm41sWAh/',
    igId: 'C6_wm41sWAh',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: ['Works so well', 'Bring to Brazil 😢'],
  },
  {
    likes: 73,
    body: 'P&G partnered with the Brave Blue World Foundation on their documentary "Our Blue World – A Water Odyssey." During the production, the team visited Cincinnati to film Mike Furey’s family, a consumer who participated in our 50 Liter Home "Connected Homes" pilot program for a year. The Fureys, a family of seven, use Cascade, Dawn Powerwash, and Tide to simplify their busy lives, get better results, and save water, energy, and time at home. #TurnToCold',
    timestamp: '2024-05-14T13:29:49+0000',
    permalink: 'https://www.instagram.com/reel/C681oOeMPoA/',
    igId: 'C681oOeMPoA',
    tags: ['Cold Water', 'Collab'],
    media_url: 'dont need',
    comments: ['Would love to watch it', '👏', '🇵🇸🔻'],
  },
  {
    likes: 129,
    body: 'Cleans soda stains like magic.',
    timestamp: '2024-05-10T22:33:24+0000',
    permalink: 'https://www.instagram.com/reel/C6zgnhDuvNb/',
    igId: 'C6zgnhDuvNb',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'Cruelty free?',
      'I love Tide and thank you for making old school powder detergent! I recently switched back to the powder and it is fantastic! 🫧💦',
      'This spring meadow heavy duty liquid is the best liquid detergent ever made!! Cleans unlike anything else, and you use less cause of the higher concentration level. Make more new scents please!!',
      "The only laundry 🧺 soap 🧼 I'll use is Tide 🌊! ❤️",
      'Wash',
      'Love Tide detergent!',
      'Please sell the detergents in the uk 🇬🇧 @tidelaundry',
    ],
  },
  {
    likes: 142,
    body: 'Is it really a bargain if this much more still doesn’t clean as well as Tide?',
    timestamp: '2024-05-10T13:25:36+0000',
    permalink: 'https://www.instagram.com/reel/C6yh-3lMS-P/',
    igId: 'C6yh-3lMS-P',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'Tide oxi is my fave 😍',
      "I'm allergic to tide, I breakout in hives every use, even with the free and clear I breakout",
      'Boycott 🛑🛑',
      'Check D M :)',
    ],
  },
  {
    likes: 69,
    body: 'Using #ColdMath with Tide is a game changer #TurnToCold thehenrys_ #TidePartner',
    timestamp: '2024-05-09T18:00:53+0000',
    permalink: 'https://www.instagram.com/reel/C6wcsQLsxPN/',
    igId: 'C6wcsQLsxPN',
    tags: ['Cold Water', 'Collab'],
    media_url: 'dont need',
    comments: [
      '🔥🔥',
      'Great tip!',
      "Name of parent company: Procter & Gamble. P&G is one of the largest clients of Israeli company Avgol, which operates a plant in the Barkan industrial complex, an illegal Israeli manufacturing settlement in the West Bank. This direct involvement in the Israeli economy strengthens its brutal policies towards the Palestinians and normalizes the Occupation, showing that P&G puts profits over justice and equality. P&G's's annual revenue in 2023 was $83.93 billion, higher than the GDP of 120 countries. We call on P&G to use its massive influence to advocate for justice in Palestine. Source @disoccupied",
    ],
  },
  {
    likes: 79,
    body: "Look! It's a BBQ stain in its natural environment. Don’t spook ‘em, let’s get the Tide... 🍃🌳🫧#laundry #laundrytok #stainremoval #budget #moneysavingtips #tide",
    timestamp: '2024-05-08T18:00:38+0000',
    permalink: 'https://www.instagram.com/reel/C6t34j5BZ2O/',
    igId: 'C6t34j5BZ2O',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'I need to try this',
      'NEW MEALS',
      "I'm excited to try the new Evo!!",
    ],
  },
];

module.exports = dummyPosts;
