const dummyPosts = [
  {
    likes: 52,
    body: 'Tide Loads of Hope is here to help.  The team is providing free laundry services starting Sunday, August 11th at the Church of Hope 2300 Lakewood Ranch Blvd, Sarasota, FL 34240 operating daily 9 AM – 5 PM local time, or until capacity is reached.',
    timestamp: '2024-08-12T16:50:28+0000',
    permalink: 'https://www.instagram.com/p/C-k8L0tu2y_/',
    igId: 'C-k8L0tu2y_',
    tags: ['Charity'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 110,
    body: 'Even the fastest men in the world get stains. When they do, Tide’s got them covered.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-08-12T00:44:23+0000',
    permalink: 'https://www.instagram.com/reel/C-jNkyOOb0Y/',
    igId: 'C-jNkyOOb0Y',

    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 99,
    body: 'When it comes to fighting the toughest stains, Tide takes home the gold.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-08-09T17:52:17+0000',
    permalink: 'https://www.instagram.com/reel/C-dUnYHO0sO/',
    igId: 'C-dUnYHO0sO',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 4743,
    body: 'Even though they’re at the top of their game, nojo18  and carl_lewis_official still get stains. Luckily, there’s Tide.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-08-07T15:04:37+0000',
    permalink: 'https://www.instagram.com/reel/C-X3-Z_OKaJ/',
    igId: 'C-X3-Z_OKaJ',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 88,
    body: 'Congratulations, Noah! We’ll make sure you’re looking your stain-free best. #Paris2024 #Olympics #Partner',
    timestamp: '2024-08-05T08:43:27+0000',
    permalink: 'https://www.instagram.com/p/C-SC4nRuir4/',
    igId: 'C-SC4nRuir4',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 101,
    body: 'The road to Olympic glory is full of stains. Thankfully, Tide’s got you covered.\n#Olympics #Paris2024 #Partner',
    timestamp: '2024-08-03T12:50:33+0000',
    permalink: 'https://www.instagram.com/reel/C-NVb3Bu5cl/',
    igId: 'C-NVb3Bu5cl',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 101,
    body: 'The toughest stains call for the hardest-working detergent. No matter how you stain, Tide’s got you covered.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-07-30T15:41:26+0000',
    permalink: 'https://www.instagram.com/reel/C-DVrvIO7HE/',
    igId: 'C-DVrvIO7HE',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 1135,
    body: 'No matter what language you speak, only Tide gets out the toughest stains.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-07-29T21:45:18+0000',
    permalink: 'https://www.instagram.com/reel/C-BasV2uRn-/',
    igId: 'C-BasV2uRn-',
    tags: ['Olympics'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 594,
    body: 'Game knows game. And when it comes to fighting stains, the legends use Tide.\n#Paris2024 #Olympics #Partner',
    timestamp: '2024-07-24T21:17:25+0000',
    permalink: 'https://www.instagram.com/reel/C90feuHPOSJ/',
    igId: 'C90feuHPOSJ',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 53,
    body: 'No matter how hard you compete, stains are no competition for the cleaning power of Tide. #theothergames',
    timestamp: '2024-07-24T13:26:37+0000',
    permalink: 'https://www.instagram.com/reel/C9zpprQOZuR/',
    igId: 'C9zpprQOZuR',
    tags: ['Olympics'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 6099,
    body: 'Stains happen to the best of us. Even nojo18 and carl_lewis_official. When they do, Tide’s got you covered.\n#Paris2024 #Olympics #TidePartner',
    timestamp: '2024-07-23T21:24:03+0000',
    permalink: 'https://www.instagram.com/reel/C9x7dSQvYkR/',
    igId: 'C9x7dSQvYkR',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 178,
    body: 'Khaby Lame knows best, and the best is Tide! America’s #1 laundry detergent brand.\n🌟 Discover the incredible journey of khaby00, the world’s biggest creator, as he dives into America’s wonders! ✨ Join Khaby as he explores the captivating people, places, and things across the nation in his brand-new unscripted series. Khaby is Coming to America is now streaming on tubi! #KhabyLame #ComingToAmerica #tide',
    timestamp: '2024-07-03T18:47:03+0000',
    permalink: 'https://www.instagram.com/p/C8-Juq5v2ZA/',
    igId: 'C8-Juq5v2ZA',
    tags: ['Olympics', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 67,
    body: 'Tide Loads of Hope and walmart  are here to help, Spencer, IA. proctergamble  is teaming up with m25m_org  to provide free laundry services starting on Saturday, from 9 AM – 5 PM, or until capacity is reached at the Walmart Supercenter at 500 11th St SW Spencer, Iowa 51301.',
    timestamp: '2024-06-28T22:02:45+0000',
    permalink: 'https://www.instagram.com/p/C8xoJqHM2fH/',
    igId: 'C8xoJqHM2fH',
    tags: ['Charity', 'Collab', 'Walmart'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 91,
    body: 'theclarajones was #TodayYearsOld when she learned that you can lift tough stains with cold water and Tide! Turn to cold with Tide to help the environment + your clothes.\n#TurnToCold #Clean #Laundry​',
    timestamp: '2024-06-24T21:54:40+0000',
    permalink: 'https://www.instagram.com/reel/C8nUACYhJ--/',
    igId: 'C8nUACYhJ--',
    tags: ['Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 109,
    body: 'Boston was #TodayYearsOld when abbylhoskins  got to drop some knowledge on him: washing clothes in cold water with Tide works on 100% of your most common stains. Tide PODS’ new formula lifts away tough stains on cold, like these grass and dirt stains, and leaves his uniform looking brand new!​\nAnd fun fact: washing on cold is also great for the environment and your wallet! It saves up to 90% of the energy on average in every wash and can save enough electricity to power the average American home for an entire hour when switching from hot to cold!',
    timestamp: '2024-06-21T14:00:49+0000',
    permalink: 'https://www.instagram.com/reel/C8evZbVJFp4/',
    igId: 'C8evZbVJFp4',
    tags: ['Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 85,
    body: 'Tide is making sure josephasthetic stays away from tees that ‘used to be white.’ Pick up some Tide with Ultra OXI White + Bright Power PODS so you can stop having to buy a new white tee after every wash. #summerwhites',
    timestamp: '2024-06-20T13:38:23+0000',
    permalink: 'https://www.instagram.com/reel/C8cIB9ouQVL/',
    igId: 'C8cIB9ouQVL',
    tags: ['Collab', 'OXI White'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 95,
    body: '#TidePartner After all these years of laundry, Tide has changed the game with a new formula! 🤯 katiepie07 #TodayYearsOld #TurnToCold #CleanTok #LaundryTok #brandnewinformation #thingsididntknow #motherhoodunplugged #TideColdWater #stainremoval #laundryhack #Tide',
    timestamp: '2024-06-06T21:08:20+0000',
    permalink: 'https://www.instagram.com/reel/C744QI6Odu_/',
    igId: 'C744QI6Odu_',

    tags: ['Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 128,
    body: '#TidePartner Were you #TodayYearsOld when you learned that turning to cold water with Tide is the ultimate life hack to having 4 girls under the age of 7!​? Stock up on Tide PODS today and switch from hot to cold! #TurnToCold #Clean #Laundry',
    timestamp: '2024-05-30T18:34:04+0000',
    permalink: 'https://www.instagram.com/reel/C7mlKFQIHIr/',
    igId: 'C7mlKFQIHIr',

    tags: ['Cold Water', 'Pods'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 70,
    body: 'It was an honor to sponsor the first ever #NationalSTEMFestival presented by usedgov and explr_media, celebrating student achievements in STEM.\nAs part of the event, Tide Senior Scientist Sammy W. sat down with students whose STEM projects are boldly imagining the future of sustainability – from water purification to repurposing food waste for textiles – to discuss how companies can innovate for a more sustainable future.\nWe can’t wait to see what else these incredible students achieve as they pursue educations and careers in #STEM!',
    timestamp: '2024-05-16T13:00:26+0000',
    permalink: 'https://www.instagram.com/p/C7B750jivO6/',
    igId: 'C7B750jivO6',

    tags: ['Sponsor', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 91,
    body: 'It’s easy to see, Tide gives you 3X more clean vs. the leading baking soda detergent.',
    timestamp: '2024-05-15T16:43:35+0000',
    permalink: 'https://www.instagram.com/reel/C6_wm41sWAh/',
    igId: 'C6_wm41sWAh',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 73,
    body: 'P&G partnered with the Brave Blue World Foundation on their documentary "Our Blue World – A Water Odyssey." During the production, the team visited Cincinnati to film Mike Furey’s family, a consumer who participated in our 50 Liter Home "Connected Homes" pilot program for a year. The Fureys, a family of seven, use Cascade, Dawn Powerwash, and Tide to simplify their busy lives, get better results, and save water, energy, and time at home. #TurnToCold',
    timestamp: '2024-05-14T13:29:49+0000',
    permalink: 'https://www.instagram.com/reel/C681oOeMPoA/',
    igId: 'C681oOeMPoA',
    tags: ['Cold Water', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 129,
    body: 'Cleans soda stains like magic.',
    timestamp: '2024-05-10T22:33:24+0000',
    permalink: 'https://www.instagram.com/reel/C6zgnhDuvNb/',
    igId: 'C6zgnhDuvNb',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 142,
    body: 'Is it really a bargain if this much more still doesn’t clean as well as Tide?',
    timestamp: '2024-05-10T13:25:36+0000',
    permalink: 'https://www.instagram.com/reel/C6yh-3lMS-P/',
    igId: 'C6yh-3lMS-P',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 69,
    body: 'Using #ColdMath with Tide is a game changer #TurnToCold thehenrys_ #TidePartner',
    timestamp: '2024-05-09T18:00:53+0000',
    permalink: 'https://www.instagram.com/reel/C6wcsQLsxPN/',
    igId: 'C6wcsQLsxPN',
    tags: ['Cold Water', 'Collab'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
  {
    likes: 79,
    body: "Look! It's a BBQ stain in its natural environment. Don’t spook ‘em, let’s get the Tide... 🍃🌳🫧#laundry #laundrytok #stainremoval #budget #moneysavingtips #tide",
    timestamp: '2024-05-08T18:00:38+0000',
    permalink: 'https://www.instagram.com/reel/C6t34j5BZ2O/',
    igId: 'C6t34j5BZ2O',
    tags: ['Advertisement'],
    media_url: 'dont need',
    comments: [
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
      'xxxxxxxxxx',
    ],
  },
];
